### ISSUE TITLE
Please add a license file

### ISSUE THREAD

**Issue by unixorn** [gusrylmubarok/gusrylmubarok-zsh-theme#1]
I'd like to add this to [awesome-zsh-plugins](https://github.com/unixorn/awesome-zsh-plugins), but it doesn't have a license file.

Please add a license file - if you don't have one in mind,  I recommend using [choosealicense.com](https://choosealicense.com) to help choose an appropriate one.

Thanks!

**Comment by gusrylmubarok** [comment]
Okay, thanks for reminding me to add a license in this repo. Now, you can see it.. I'm glad you'll add it in the [awesome-zsh plugin.](https://github.com/unixorn/awesome-zsh-plugins)

**Comment by unixorn** [comment]
Thanks, adding it to the list.
